# -*- coding: utf-8 -*-
"""qr_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0wZV7sf3tNMAPer2trnBQFpE-9PcFRW
"""

# Install the required libraries
!pip install qrcode[pil]

# Import libraries
import qrcode
from PIL import Image

# Function to generate and display QR code
def generate_qr_code(data, filename="qrcode.png"):
    # Create QR code instance
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )

    # Add data to the QR code
    qr.add_data(data)
    qr.make(fit=True)

    # Create an image of the QR code
    img = qr.make_image(fill="black", back_color="white")
    img.save(filename)

    # Display the image
    display(img)

# Example usage
data_to_encode = "https://www.example.com"
generate_qr_code(data_to_encode, "example_qr_code.png")